name: Lint and Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/ignitionstack
      GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.23"
          cache: false
      - run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
  test:
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        go: ["1.23"]
        test-tags:
          ["", "-race"]
        include:
          - os: ubuntu-24.04
            go-build: ~/.cache/go-build
    name: ${{ matrix.os }} @ Go ${{ matrix.go }} ${{ matrix.test-tags }}
    runs-on: ${{ matrix.os }}
    env:
      GO111MODULE: on
      TESTTAGS: ${{ matrix.test-tags }}
      GOPROXY: https://proxy.golang.org
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: true

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Tests
        run: go test ./... -coverprofile=coverage.out -covermode=atomic

      - name: Format
        if: matrix.go-version == '1.22.x'
        run: diff -u <(echo -n) <(gofmt -d .)