name: test

on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  contents: read

jobs:
  test:
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        go: ["1.24"]
        test-tags: ["", "-race"]
        include:
          - os: ubuntu-24.04
            go-build: ~/.cache/go-build
    name: ${{ matrix.os }} @ Go ${{ matrix.go }} ${{ matrix.test-tags }}
    runs-on: ${{ matrix.os }}
    env:
      GO111MODULE: on
      TESTTAGS: ${{ matrix.test-tags }}
      GOPROXY: https://proxy.golang.org
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: true

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Tests
        run: go test ./... -coverprofile=coverage.out -covermode=atomic

      - name: Format
        if: matrix.go-version == '1.22.x'
        run: diff -u <(echo -n) <(gofmt -d .)
